-- Test Schema Initialization for H2 Database
-- Creates required schemas for unit tests

CREATE SCHEMA IF NOT EXISTS common;
CREATE SCHEMA IF NOT EXISTS production;
CREATE SCHEMA IF NOT EXISTS qms;
CREATE SCHEMA IF NOT EXISTS inventory;
CREATE SCHEMA IF NOT EXISTS bom;
CREATE SCHEMA IF NOT EXISTS customer_supplier;
CREATE SCHEMA IF NOT EXISTS material;
CREATE SCHEMA IF NOT EXISTS purchase;
CREATE SCHEMA IF NOT EXISTS sales;
CREATE SCHEMA IF NOT EXISTS wms;
CREATE SCHEMA IF NOT EXISTS equipment;
CREATE SCHEMA IF NOT EXISTS employee;
CREATE SCHEMA IF NOT EXISTS approval;
CREATE SCHEMA IF NOT EXISTS skill;
CREATE SCHEMA IF NOT EXISTS holiday;
CREATE SCHEMA IF NOT EXISTS alarm;
